#!/bin/sh
#
# git pre-commit hook
#
# This script should be copied into your local clones .git/hooks/
# directory and made executable (`chmod +x`).
#
# After that, the script will run before every call to git commit and
# check if grunt is installed and if `grunt lint` comes back successfully.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=false

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

GIT_ROOT="$(git rev-parse --show-toplevel)"
if [ ! -x $GIT_ROOT/node_modules/.bin/grunt ] || [ ! -x $(which grunt) ]; then
	cat <<\EOF
Error: You are trying to commit code or changes to the repository without the ability to
lint or validate prior to commit.

Please make sure you have grunt installed in your local or global path!

EOF
	exit 1
fi

#
# Bad files
#
BAD_FILES=$GIT_ROOT/.git/hooks/pre-commit-bad-files.dat

if [ ! -f "$BAD_FILES" ]; then
	echo Please ensure $BAD_FILES exists!
	exit 1
fi

for file in $(cat $BAD_FILES)
do
    if [ -e "$GIT_ROOT/$file" ]; then
    	echo "Private SOASTA file check: $file exists"; exit 1
    fi
done

#
# BOOMR.session
#
grep -i BOOMR.session $GIT_ROOT/*.js | grep -v .git && echo BOOMR.session exists && exit 1
grep -iR BOOMR.session $GIT_ROOT/plugins/ | grep -v .git && echo BOOMR.session exists && exit 1
grep -iR BOOMR.session $GIT_ROOT/tests/ | grep -v .git && echo BOOMR.session exists && exit 1

#
# SOASTA PRIVATE
#
grep -i "SOASTA PRIVATE" $GIT_ROOT/*.js | grep -v .git && echo "SOASTA PRIVATE" exists && exit 1
grep -iR "SOASTA PRIVATE" $GIT_ROOT/plugins/ | grep -v .git && echo "SOASTA PRIVATE" exists && exit 1
grep -iR "SOASTA PRIVATE" $GIT_ROOT/tests/ | grep -v .git && echo "SOASTA PRIVATE" exists && exit 1

#
# go-mpulse
#
grep -i go-mpulse $GIT_ROOT/*.js | grep -v .git && echo go-mpulse exists && exit 1
grep -iR go-mpulse $GIT_ROOT/plugins/ | grep -v .git && echo go-mpulse exists && exit 1
grep -iR go-mpulse $GIT_ROOT/tests/ | grep -v .git && echo go-mpulse exists && exit 1

#
# API_KEY
#
grep -i API_KEY $GIT_ROOT/*.js | grep -v .git && echo API_KEY exists && exit 1
grep -iR API_KEY $GIT_ROOT/plugins/ | grep -v .git && echo API_KEY exists && exit 1
grep -iR API_KEY $GIT_ROOT/tests/ | grep -v .git && echo API_KEY exists && exit 1

#
# Lint
#
GRUNT_EXEC=$(which grunt || $GIT_ROOT/node_modules/.bin/grunt)
$GRUNT_EXEC --gruntfile $GIT_ROOT/Gruntfile.js lint
